source "https://rubygems.org"

gem 'rails', '7.1.3'
gem 'sqlite3', '~> 1.4'
gem 'puma'

# Include your engine gem from local path:
gem 'rails_api_guard',  path: '../../..'

# Other dependencies as needed, e.g. sprockets-rails:
gem 'sprockets-rails'

gem 'dotenv'
gem 'pry'